language: go

go:
  - 1.11.x
  - 1.12.x
  - master

matrix:
  fast_finish: true
  allow_failures:
    - go: master

script:
  - go get -d -t -v ./...
  - go build -v ./...
  - go test -v ./...

notifications:
  email:
    recipients:
	  - emergentdev@grey.colorado.edu
	on_success: change
	on_failure: always

