Name = "gi"
Desc = ""
Version = "v2.0.0-dev0.0.1"
Type = "Library"

[Build]
  Package = "."

[Install]
  Package = "."

[Log]
  Target = "android"
  Keep = false
  All = "F"

[Release]
  VersionFile = "gi/version.go"
  Package = "gi"
