Name = "grows"
Desc = ""
Version = "v0.3.0"
Type = "TypeLibrary"

[Build]
  Package = "."

[Colorgen]
  Source = "colors.xml"
  Output = "colorgen.go"
  Package = "main"
  Comment = ""

[Install]
  Package = "."

[Log]
  Target = "android"
  Keep = false
  All = "F"

[Release]
  VersionFile = "version.go"
  Package = "grows"

[Generate]
  Dir = "."
  Output = "gokigen.go"
  [Generate.Enumgen]
    Dir = "."
    Output = "enumgen.go"
    SQL = false
    Text = true
    JSON = false
    YAML = false
    GQL = false
    Transform = ""
    TrimPrefix = ""
    AddPrefix = ""
    LineComment = false
    Comment = ""
