Name = "goki"
Desc = "Command line and GUI tools for developing apps and libraries using the GoKi framework."
Version = "v0.0.0"

[Build]
  Package = "."

  [[Build.Platform]]
    OS = ""
    Arch = ""

[Colorgen]
  Source = "colors.xml"
  Output = "colorgen.go"
  Package = "goki"
  Comment = "These are the color schemes"

[Install]
  Package = "."
  Target = [""]

[Log]
  Target = "android"
  Keep = false
  All = ""
