Name = "tools"
Desc = ""
Version = "v0.0.0"

[Build]
  Package = ""

[Colorgen]
  Source = ""
  Output = ""
  Package = ""
  Comment = ""

[Install]
  Package = ""

[Log]
  Target = ""
  Keep = false
  All = ""
