Name = "goki"
Desc = "Command line and GUI tools for developing apps and libraries using the GoKi framework."
Version = "v0.1.22"
Type = "App"

[Build]
  Package = "."
  Output = ""
  Rebuild = false
  Install = false
  PrintOnly = false
  Print = false
  Trimpath = false
  Work = false
  IOSVersion = "13.0"
  AndroidMinSDK = 23
  AndroidTargetSDK = 29
  BundleID = ""

[Colorgen]
  Source = "colors.xml"
  Output = "colorgen.go"
  Package = "goki"
  Comment = "These are the color schemes"

[Install]
  Package = "."
  Target = [""]

[Log]
  Target = "android"
  Keep = false
  All = "F"

[Release]
  VersionFile = "version.go"
  Package = "main"

[Generate]
  Dir = "."
  Output = "gokigen.go"
  AddKiTypes = false
  [Generate.Enumgen]
    Dir = "."
    Output = "enumgen.go"
    Transform = ""
    TrimPrefix = ""
    AddPrefix = ""
    LineComment = false
    AcceptLower = true
    Text = true
    JSON = false
    YAML = false
    SQL = false
    GQL = false
  [Generate.Gtigen]
    Dir = "."
    Output = "gtigen.go"
    AddTypes = false
    AddMethods = false
    AddFuncs = false
    Instance = false
    TypeVar = false
