name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.17.x, 1.16.x]
        platform: [ubuntu-latest]  # not macos-latest
        env:
          - GO111MODULE=off
          - GO111MODULE=on

    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache-Go
      uses: actions/cache@v1
      with:
        path: |
            ~/go/pkg/mod              # Module download cache
            ~/.cache/go-build         # Build cache (Linux)
            ~/Library/Caches/go-build # Build cache (Mac)
            '%LocalAppData%\go-build' # Build cache (Windows)

        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: |
        make test

    - name: Upload-Coverage
      if: matrix.platform == 'ubuntu-latest'
      run: bash <(curl -s https://codecov.io/bash)

